- generic [ref=e2]:
  - generic "Situbondo Messenger game scene" [ref=e3]
  - region "Game status":
    - generic:
      - generic:
        - generic: Letters
        - strong: 0/7
      - generic:
        - generic: Time
        - strong: "900"
      - generic:
        - generic: Bonus
        - strong: +0s
    - 'generic "Route progress: 0 of 7 deliveries"'
  - 'region "Current delivery: Alun-Alun Situbondo, 85 meters away"':
    - generic:
      - generic: Next Delivery
      - strong: Alun-Alun
      - generic: 85 m · Nearby
  - generic [ref=e4]:
    - generic [ref=e5]: Situbondo · Jawa Timur
    - img "Envelope" [ref=e6]
    - heading "Situbondo Messenger" [level=1] [ref=e11]:
      - text: Situbondo
      - text: Messenger
    - paragraph [ref=e12]: Jelajahi zona nyata 1 km dari Alun-Alun. Area di luar masih dikembangkan.
    - generic "Map coverage and scale" [ref=e13]:
      - generic [ref=e14]:
        - strong [ref=e15]: 1 km
        - text: radius
      - generic [ref=e16]:
        - strong [ref=e17]: 3,243
        - text: buildings
      - generic [ref=e18]:
        - strong [ref=e19]: "102"
        - text: animated buildings
      - strong [ref=e21]: 1 unit = 5 m
      - generic [ref=e22]:
        - strong [ref=e23]: 3.14 km²
        - text: mapped
      - generic [ref=e24]:
        - strong [ref=e25]: Restricted
        - text: beyond 1 km
    - generic "Controls" [ref=e26]:
      - generic [ref=e27]:
        - generic [ref=e28]: WASD
        - text: or arrows to move
      - generic [ref=e29]: Drag anywhere on touch screens
      - generic [ref=e30]:
        - generic [ref=e31]: Shift
        - text: to run
      - generic [ref=e32]:
        - generic [ref=e33]: Space
        - text: to stop
    - button "Mulai Rute" [ref=e34] [cursor=pointer]
    - generic [ref=e35]: Map data © OpenStreetMap contributors · ODbL
  - generic "Movement controls":
    - generic:
      - generic:
        - generic: WASD
        - text: Move ·
        - generic: Shift
        - text: Run ·
        - generic: Space
        - text: Stop
    - button "Stop" [ref=e36] [cursor=pointer]:
      - generic [ref=e38]: Stop